jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read # This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Create and activate virtual environment
        run: |
          python -m venv antenv
          source antenv/bin/activate
          python -m pip install --upgrade pip

      - name: Install dependencies from requirements.txt
        run: |
          source antenv/bin/activate
          pip install -r requirements.txt

      # Debugging step to verify all dependencies are installed
      - name: List installed dependencies
        run: |
          source antenv/bin/activate
          pip list

      - name: Zip artifact for deployment
        run: |
          zip release.zip ./* -r

      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: |
            release.zip
            !antenv/