name: Build and deploy Python app to Azure Web App - emotionchat2

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read # Required for actions/checkout

    steps:
      # Step 1: Checkout repository
      - uses: actions/checkout@v4

      # Step 2: Set up Python version
      - name: Set up Python 3.9
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      # Step 3: Install dependencies in a clean virtual environment
      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install fastapi
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install uvicorn
        # Exclude virtual environment from deployment artifact
        env:
          PIP_CACHE_DIR: .pip_cache

      # Step 4: List installed dependencies (for debugging)
      - name: List installed dependencies
        run: |
          source venv/bin/activate
          pip list

      # Step 5: Prepare deployment package
      - name: Create deployment package
        run: |
          zip -r release.zip . -x ".git/*" "venv/*" "*.pytest_cache/*" ".pip_cache/*" "*.github/*"

      # Step 6: Upload artifact for deployment
      - name: Upload deployment artifact
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write # Required for requesting the JWT
      contents: read # Required for actions/checkout

    steps:
      # Step 1: Download artifact from build job
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: python-app

      # Step 2: Unzip artifact
      - name: Unzip artifact
        run: unzip release.zip

      # Step 3: Login to Azure
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_745F5A120B294AD9A054E688121B602B }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_4046C49CF62C42BBB437FE1663FD5941 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_AA68078924D44405BA62A0B3AF803302 }}

      # Step 4: Deploy to Azure Web App
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'emotionchat2'
          slot-name: 'Production'