name: Build and deploy Python app to Azure Web App - emotionchat2

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write # This is required for requesting the JWT
      contents: read # This is required for actions/checkout

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Python 3.9
      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      # Step 3: Create and activate the virtual environment
      - name: Create and activate virtual environment
        run: |
          python -m venv antenv
          source antenv/bin/activate
          python -m pip install --upgrade pip

      # Step 4: Install dependencies
      - name: Install dependencies
        run: |
          source antenv/bin/activate
          pip install -r requirements.txt

      # Step 5: Optional - Run tests (if applicable)
      # Add tests here if needed, e.g., pytest or other test frameworks.

      # Step 6: Login to Azure
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_745F5A120B294AD9A054E688121B602B }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_4046C49CF62C42BBB437FE1663FD5941 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_AA68078924D44405BA62A0B3AF803302 }}

      # Step 7: Deploy to Azure Web App
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'emotionchat2'
          slot-name: 'Production'